bullavka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin-bullavka-privet/', admin.site.urls),
    path('', include('main.urls')),
    path('about/', include('gallery.urls')),
    path('jobs/', include('jobs.urls')),
    path('partners/', include('partners.urls')),
    path('cooperation/', include('cooperation.urls')),
    path('contacts/', include('contacts.urls')),
    path('news/', include('news.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *


urlpatterns = [
   path('', Jobs.as_view(), name='jobs_url'),
   path('form', JobFormModel.as_view(), name='form_url'),
   path('ajax/load-jobnames/', load_jobnames, name='ajax_load_jobnames'),
   path('ajax/load-jobnames-jobs/', load_jobnames_jobs, name='ajax_load_jobnames_jobs'),
]

jobs/models.py
from django.db import models


class Coffeehouse(models.Model):
   name = models.CharField(max_length=64, blank=True, null=True, default=None)
   is_active = models.BooleanField(default=True)

   def __str__(self):
       return "%s" % self.name

   class Meta:
       verbose_name = 'Кофейня'
       verbose_name_plural = 'Кофейни'

class JobName(models.Model):
   job_name = models.CharField(max_length=64, null=True, default=None)
   coffeehouse = models.ForeignKey(Coffeehouse, on_delete=models.CASCADE)

   def __str__(self):
       return "%s" % self.job_name

   class Meta:
       verbose_name = 'Название вакансии'
       verbose_name_plural = 'Названия вакансий'


class Job(models.Model):
   coffeehouse = models.ForeignKey(Coffeehouse, on_delete=models.SET_NULL, null=True)
   jobname = models.ForeignKey(JobName, on_delete=models.SET_NULL, null=True)
   salary = models.CharField(max_length=100, blank=True, null=True, default=None)
   workplace = models.CharField(max_length=100, blank=True, null=True, default=None)
   timetable = models.CharField(max_length=100, blank=True, null=True, default=None)
   conditions = models.TextField(blank=True, null=True, default=None)
   responsibilities = models.TextField(blank=True, null=True, default=None)
   education = models.CharField(max_length=100, blank=True, null=True, default=None)
   experience = models.CharField(max_length=100, blank=True, null=True, default=None)
   requirements = models.TextField(blank=True, null=True, default=None)

   class Meta:
       verbose_name = 'Вакансия'
       verbose_name_plural = 'Вакансии'

jobs/forms.py
from django import forms
from .models import JobName, Job

class JobForm(forms.ModelForm):
   class Meta:
       model = Job
       fields = ('coffeehouse', 'jobname')

   def __init__(self, *args, **kwargs):
       super(JobForm, self).__init__(*args, **kwargs)
       self.fields['jobname'].widget.attrs['class'] = 'js-select3'
       self.fields['coffeehouse'].widget.attrs['class'] = 'js-select2'
       self.fields['jobname'].queryset = JobName.objects.none()




       if 'coffeehouse' in self.data:
           try:
               coffeehouse_id = int(self.data.get('coffeehouse'))

               self.fields['jobname'].queryset = JobName.objects.filter(coffeehouse_id=coffeehouse_id).order_by('job_name')

           except (ValueError, TypeError):
               pass  # invalid input from the client; ignore and fallback to empty City queryset
       elif self.instance.pk:
           self.fields['jobname'].queryset = self.instance.coffeehouse.jobname_set.order_by('job_name')

jobs/views.py
from .models import *
from django.views.generic import View
from .forms import *
import smtplib
from django.core.mail import BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from main.models import Logo



class Jobs(View):
    def get(self, request):
       coffeehouses = Coffeehouse.objects.all()
       logo = Logo.objects.latest('pk')
       return render(request, 'jobs/job.html', context={'coffeehouses': coffeehouses,
                                                        'logo': logo})



def load_jobnames_jobs(request):
   coffeehouse_id = request.GET.get('coffeehouse')
   jobnames = JobName.objects.filter(coffeehouse_id=coffeehouse_id).order_by('job_name')
   jobs = Job.objects.filter(coffeehouse_id=coffeehouse_id)
   return render(request, 'jobs/jobs_list.html', context={'jobnames': jobnames,
                                                          'jobs':jobs})



class JobFormModel(View):
   def get(self, request):
      logo = Logo.objects.latest('pk')
      form = JobForm()
      coffeehouses = Coffeehouse.objects.all()
      return render(request, 'jobs/job_form.html', context={'form':form,
                                                            'coffeehouses': coffeehouses,
                                                            'logo': logo})

   def post(self, request):
      if request.method == 'POST':
         form = JobForm(request.POST)
         if form.is_valid():

            coffeehouse = form.cleaned_data['coffeehouse'].name
            jobname = form.cleaned_data['jobname'].job_name
            firstname = request.POST['Fname']
            secondname = request.POST['Sname']
            birth_date = request.POST['date']
            citizenship = request.POST['citizenship']
            tel = request.POST['tel']
            email = request.POST['email']
            agreement = request.POST['agree']



            try:
               mail_user_ = '################'
               mail_password_ = '###############'
               to = 'Bullavkamoscow@gmail.com'
               sent_from = email
               email_text = 'Subject: {}\n\n{}'.format(firstname + ' ' + secondname + ' | ' +
                                                       coffeehouse + ' | ' + jobname, 'Кофейня: ' + coffeehouse
                                                       + '\nВакансия: ' + jobname + '\nИмя: ' + firstname +
                                                       '\nФамилия: ' + secondname + '\nEmail: ' + email +
                                                       '\nНомер телефона: ' + tel + '\nГражданство: ' + citizenship
                                                       + '\nДата рождения: ' + birth_date + '\n' + ('Нет, я против этого','Я согласен с тем, '
                                                                                            'что мои персональные данные будут'
                                                                                            ' использоваться компанией.')[agreement == 'agree']).encode('utf-8')

               server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
               server.ehlo()
               server.login(mail_user_, mail_password_)
               server.sendmail(sent_from, to, email_text)
               server.close()
               print('Email sent!')

            except BadHeaderError:
               return HttpResponse('Invalid header found.')
            return redirect('form_url')

      return redirect('form_url')




def load_jobnames(request):
   coffeehouse_id = request.GET.get('coffeehouse')
   jobnames = JobName.objects.filter(coffeehouse_id=coffeehouse_id).order_by('job_name')
   return render(request, 'jobs/coffeehouse_dropdown_list_options.html', context={'jobnames': jobnames})

jobs/templates/jobs/coffeehouse_dropdown_list_options.html
<option value="">Выберите вакансию</option>
{% for x in jobnames %}
<option value="{{ x.pk }}">{{ x.job_name }}</option>
{% endfor %}

jobs/templates/jobs/job.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>

	<meta charset="utf-8">
	<!-- <base href="/"> -->

	<title>БулЛавка</title>
	<meta name="description" content="">

	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- Template Basic Images Start -->
    <meta property="og:image" content="{% static 'img/favicon/newfavi.ico' %}">
    <meta property="vk:image" content="{% static 'img/obloj.png' %}">
	<link rel="icon" href="{% static 'img/favicon/newfavi.ico' %}">
	<!-- Template Basic Images End -->

	<!-- Custom Browsers Color Start -->
	<meta name="theme-color" content="#000">
  <!-- Custom Browsers Color End -->
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&amp;subset=cyrillic" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}"/>
<!-- // Add the new slick-theme.css if you want the default styling -->
	
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
		rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/main.css' %}">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.js"></script>
</head>

<body>



	<!-- Nav-bar  -->
<header class="job">

	<div  class="container">



		<div class="row">

			<div class="col-2 logo ">
				<img src="/media/{{ logo.PHOTO }}" alt="logo">
			</div>

			<div class="col-8 ">
				<div class="nav">
					<a href="{% url 'main_url' %}" class="one nav__item active">Главная</a>
					<a href="{% url 'news_url' %}" class="two nav__item">Новости</a>
					<a href="{% url 'gallery_url' %}" class="two nav__item">О нас</a>
					<a href="{% url 'jobs_url' %}" class="act three nav__item">Наши вакансии</a>
					<a href="{% url 'partners_url' %}" class=" four nav__item">Наши партнеры</a>
					<a href="{% url 'cooperation_url' %}" class="nav__item">Сотрудничество</a>
					<a href="{% url 'contacts_url' %}" class="nav__item">Контакты</a>
				</div>

			</div>
			<div class="col-2 ">
				<div class="social">
					<a target="_blank" href="https://www.instagram.com/bullavka_moscow/"><img src="{% static 'img/instagram.svg' %}" alt="instagram"></a>
					<a target="_blank" href="https://vk.com/bullavka_moscow"><img src="{% static 'img/vk.svg' %}" alt="vk"></a>
					<a target="_blank" href="https://www.facebook.com/bullavkamoscow/"><img src="{% static 'img/facebook.svg' %}" alt="facebook"></a>
				</div>
			</div>

		</div>

	</div>

  <div class="containter">
    <div class="row">
      <div class="col-12">
        <h2 class="h2">Наши вакансии</h2>
      </div>
    </div>
  </div>
</header>
{% include 'mobile_nav.html' %}

<div class="overlay"></div>


<main class='main-job'>
  <div class="container">
		<div class="row">

			<div class="col-xs-12 col-md-6 ">
				<a href="{% url 'form_url' %}" class="btn btn-contact btn-job">Заполнить анкету</a>
			</div>
		</div>
  <div class="row">
    <div class="col-xs-12 col-md-6 job-cont">

			
			
				
				
				





<form method="post" id="jobs" data-jobnames-url="{% url 'ajax_load_jobnames_jobs' %}" novalidate>
	<select class="js-select2" id="extractCoffeehouse">
		<option value="" >Выберите кофейню</option>
		{% for x in coffeehouses %}
		<option value="{{ x.pk }}">{{ x }}</option>
		{% endfor %}

</select>

{% csrf_token %}
</form>

<ul id="enterJobnames">

</ul>


 <script>
   $("#extractCoffeehouse").change(function () {
     var url = $("#jobs").attr("data-jobnames-url");
     var coffeehouseId = $(this).val();

     $.ajax({
       url: url,
       data: {
         'coffeehouse': coffeehouseId
       },
       success: function (data) {
         $("#enterJobnames").html(data);
       }
     });

   });
 </script>







</main>


{% include 'footer.html' %}



<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script> -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.js"></script>

 <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->
	<!-- <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script> -->
  <!-- <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script> -->
	<!-- <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>  -->
	 <!-- <script src="{% static 'js/scripts.min.js' %}"></script> -->
	 <script>
	 $(document).ready(function() {
  $(".textBoxAccordionEl:not(.fixed) .textBoxAccordionElTitle").click(function() {
      $(this).closest(".textBoxAccordionEl").toggleClass("open")
  });
	 });
	 </script>
	<script>
		"use strict";

		$(document).ready(function domReady() {
			$(".js-select2").select2({
					placeholder: "Выберите кофейню",
					theme: "material"
			});

			$(".select2-selection__arrow")
					.addClass("material-icons")
					.html("arrow_drop_down");
		});
		</script>
		<script>

			$('.burger, .overlay').click(function(){
				$('.burger').toggleClass('clicked');
				$('.overlay').toggleClass('show');
				$('nav').toggleClass('show');
				$('body').toggleClass('overflow');
			});</script>
</body>
</html>

jobs/templates/jobs/job_form.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>

  <meta charset="utf-8">
  <!-- <base href="/"> -->

  <title>БулЛавка</title>
  <meta name="description" content="">

  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <!-- Template Basic Images Start -->
    <meta property="og:image" content="{% static 'img/favicon/newfavi.ico' %}">
    <meta property="vk:image" content="{% static 'img/obloj.png' %}">
	<link rel="icon" href="{% static 'img/favicon/newfavi.ico' %}">


  <!-- Custom Browsers Color Start -->
  <meta name="theme-color" content="#000">
 <!-- Custom Browsers Color End -->
 <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&amp;subset=cyrillic" rel="stylesheet">
 <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}"/>
<!-- // Add the new slick-theme.css if you want the default styling -->
 <link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
		rel="stylesheet">
</head>

<body>


  <!-- Nav-bar  -->
<header class="job">

  <div  class="container">



     <div class="row">

        <div class="col-2 logo">
           <img src="/media/{{ logo.PHOTO }}" alt="logo">
        </div>

        <div class="col-8 ">
           <div class="nav">
					<a href="{% url 'main_url' %}" class="one nav__item active">Главная</a>
          <a href="{% url 'news_url' %}" class="two nav__item">Новости</a>
					<a href="{% url 'gallery_url' %}" class="two nav__item">О нас</a>
					<a href="{% url 'jobs_url' %}" class=" act three nav__item">Наши вакансии</a>
					<a href="{% url 'partners_url' %}" class=" four nav__item">Наши партнеры</a>
					<a href="{% url 'cooperation_url' %}" class="nav__item">Сотрудничество</a>
					<a href="{% url 'contacts_url' %}" class="nav__item">Контакты</a>
           </div>

        </div>
        <div class="col-2 ">
           <div class="social">
              <a target="_blank" href="https://www.instagram.com/bullavka_moscow/"><img src="{% static 'img/instagram.svg' %}" alt="instagram"></a>
              <a target="_blank" href="https://vk.com/bullavka_moscow"><img src="{% static 'img/vk.svg' %}" alt="vk"></a>
              <a target="_blank" href="https://www.facebook.com/bullavkamoscow/"><img src="{% static 'img/facebook.svg' %}" alt="facebook"></a>

           </div>
        </div>

     </div>

  </div>
 <div class="containter ">
   <div class="row">
     <div class="col-12">
       <h2 class="h2">Наши вакансии</h2>
     </div>
   </div>
 </div>
</header>
{% include 'mobile_nav.html' %}

<div class="overlay"></div>
<main class='blank-main'>
 <div class="container">
   <div class="row backing">
     <div class="col-12 bac">
         <a class='back'href="{% url 'jobs_url' %}">Назад к вакансиям</a>
     </div>
   </div>
   <div class="row">
     <div class="col-12">
       <h2 class="mini-h2">
         АНКЕТА
       </h2>

     </div>
   </div>

     <div class="row">
         <div class="col-sm-12  second">

             <!--<div class="custom-select">-->

 <form method="post" id="jobForm" action="{% url 'form_url' %}" data-jobnames-url="{% url 'ajax_load_jobnames' %}">
   {% csrf_token %}

   {{ form.coffeehouse }}
   {{ form.jobname }}





 <script>
   $("#id_coffeehouse").change(function () {
     var url = $("#jobForm").attr("data-jobnames-url");
     var coffeehouseId = $(this).val();

     $.ajax({
       url: url,
       data: {
         'coffeehouse': coffeehouseId
       },
       success: function (data) {
         $("#id_jobname").html(data);
       }
     });

   });
 </script>
	<script>

    $('.burger, .overlay').click(function(){
      $('.burger').toggleClass('clicked');
      $('.overlay').toggleClass('show');
      $('nav').toggleClass('show');
      $('body').toggleClass('overflow');
    });</script>



     <!---->
   <div class="row">
     <div class="col-12">


         </div>
       </div>

       <div class="row">
         <div class="col-sm-12 col-md-6">
             <div class="input-field input-field--inline">
                 <input type="text" name="Fname" id="Fname" placeholder="Имя" required="" >
               </div>
         </div>
         <div class="col-sm-12 col-md-6">
             <div class="input-field input-field--inline">
                 <input type="text" name="Sname" id="Sname" placeholder="Фамилия" required="" >
               </div>
         </div>
       </div>
       <div class="row">
           <div class="col-sm-12 col-md-6">
               <div class="input-field input-field--inline">
                   <input type="text" name="date" id="dateBirthday" placeholder="Дата рождения" required="" >
                 </div>
           </div>
           <div class="col-sm-12 col-md-6">
               <div class="input-field input-field--inline">
                   <input type="text" name="citizenship" id="citizenship" placeholder="Гражданство" required="" >
                 </div>
           </div>
         </div>

         <div class="row">
             <div class="col-sm-12 col-md-6">
                 <div class="input-field input-field--inline">
                     <input type="tel" name="tel" id="tel" placeholder="Номер телефона" required="" >
                   </div>
             </div>
             <div class="col-sm-12 col-md-6">
                 <div class="input-field input-field--inline">
                     <input type="email" name="email" id="email" placeholder="Email " required="" autocomplete="mail">
                   </div>
             </div>
           </div>
             <div class="row">
                 <div class="col-sm-12 col-md-6 second">



                     </div>
                   </div>

                   <div class="row">
                     <div class="col-12">
                         <div class="input-field">
                             <input type="checkbox" name="agree" id="agree" required value="agree">
                             <label for="agree">Я согласен с тем, что мои персональные данные будут использоваться компанией</label>
                           </div>
                     </div>
                   </div>

                   <div class="row">
                     <div class="col-12 send">
                         <button class="btn btn-contact ">ОТПРАВИТЬ АНКЕТУ</button>
                     </div>
                   </div>


     </form>
     </div>
</main>

{% include 'footer.html' %}

</main>



<script>
    "use strict";

    $(document).ready(function domReady() {
        $(".js-select2").select2({
                placeholder: "Выберите кофейню",
                "language": "ru-RU",
                theme: "material",
                language: {
                    noResults: function (params) {
                      return "Для просмотра вакансий — выберите кофейню";
                    }
                }
        });

        $(".select2-selection__arrow")
                .addClass("material-icons")
                .html("arrow_drop_down");
    });

</script>
<script>
    "use strict";

    $(document).ready(function domReady() {
        $(".js-select3").select2({
                placeholder: "Выберите вакансию",
                "language": "ru-RU",
                theme: "material",
                language: {
                    noResults: function (params) {
                      return "Для просмотра вакансий — выберите кофейню";
                    }
                }
        });

        $(".select2-selection__arrow")
                .addClass("material-icons")
                .html("arrow_drop_down");
    });

</script>
</body>
</html>

jobs/templates/jobs/jobs_list.html
 <div class="tab-frame">

          {% for x in jobs %}

            <input type="radio"  name="tab" id="tab{{ forloop.counter }}">
            <label class='r{{ forloop.counter }} r' for="tab{{ forloop.counter }}">{{ x.jobname }}</label>

            {% endfor %}


       <!--ALL JOBS-->

          {% for x in jobs %}
        <div class="tab">
          <h3 class="mini-header">{{ x.jobname }}</h3>
        {% if x.salary %}
          <p><strong>Заработная плата</strong></p>
          <p class="mini-text">{{ x.salary }}</p>
                {% endif %}

            {% if x.workplace %}
          <p><strong>Место работы</strong></p>
          <p class="mini-text">{{ x.workplace }} </p>
            {% endif %}

            {% if x.timetable %}
          <p><strong>График работы</strong></p>
          <p class="mini-text">{{ x.timetable }}</p>
            {% endif %}

            {% if x.conditions %}
          <p><strong>Условия</strong></p>
          <p class="mini-text"> {{ x.conditions }}
            {% endif %}

            {% if x.responsibilities %}
          <p><strong>Обязанности</strong></p>
            {{ x.responsibilities }}
            {% endif %}


          <h5 class="h5">ТРЕБОВАНИЯ К КАНДИДАТУ*</h5>

            {% if x.education %}
          <p><strong> Образование</strong></p>
          <p class="mini-text">{{ x.education }}</p>
             {% endif %}

           {% if x.experience %}
          <p><strong> Опыт работы </strong></p>
          <p class="mini-text">{{ x.experience }}</p>
            {% endif %}

             {% if x.requirements %}
          <p><strong>Требования</strong></p>
            {{ x.requirements }}
            {% endif %}


        </div>
        {% endfor %}
 </div>

 <div class="iphone-check">

{% for x in jobs %}
<div class="textBoxAccordionEl ">
	<div class="textBoxAccordionElTitle">{{ x.jobname }}</div>
	<div class="textBoxAccordionElContent">
			<div class="tab">
                    {% if x.job_name %}
					<h3 class="mini-header">{{ x.jobname }}</h3>
                    {% endif %}

                    {% if x.salary %}
					<p><strong>Заработная плата</strong></p>
					<p class="mini-text">{{ x.salary }}</p>
                    {% endif %}

                    {% if x.workplace %}
					<p><strong>Место работы</strong></p>
					<p class="mini-text">{{ x.workplace }}</p>
                    {% endif %}

                    {% if x.timetable %}
					<p><strong>График работы</strong></p>
					<p class="mini-text">{{ x.timetable }}</p>
                    {% endif %}

                    {% if x.conditions %}
					<p><strong>Условия</strong></p>
					<p class="mini-text">{{ x.conditions }}</p>
                    {% endif %}

                    {% if x.responsibilities %}
					<p><strong>Обязанности</strong></p>
                    {{ x.responsibilities }}
                    {% endif %}

					<h5 class="h5">ТРЕБОВАНИЯ К КАНДИДАТУ*</h5>

                    {% if x.education %}
					<p><strong> Образование</strong></p>
					<p class="mini-text">{{ x.education }}</p>
                    {% endif %}

                    {% if x.experience %}
					<p><strong> Опыт работы </strong></p>
					<p class="mini-text">{{ x.experience }}</p>
                    {% endif %}

                    {% if x.requirements %}
					<p><strong>Требования</strong></p>
					{{ x.requirements }}
                    {% endif %}


				</div>                 </div>
</div>
{% endfor %}
</div>
<script>
$(document).ready(function() {
$(".textBoxAccordionEl:not(.fixed) .textBoxAccordionElTitle").click(function() {
$(this).closest(".textBoxAccordionEl").toggleClass("open")
});
});
    </script>